services:
  - type: web
    name: web
    runtime: node
    region: oregon # optional (defaults to oregon)
    plan: starter # optional (defaults to starter instance type)
    branch: main # optional (defaults to master)
    buildCommand: npm install --force && npm run build
    startCommand: npm run db:migrate && node build/index.js
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tofustack
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: redis
          type: redis
          property: connectionString
      - key: PUBLIC_ORIGIN
        fromService:
          name: web
          type: web
          property: host
  - type: redis
    name: redis
    ipAllowList: [] # Only allow internal connections

databases:
  - name: db
    databaseName: tofustack
    ipAllowList: []
